language: r
cache: packages

matrix:
  include:
    - r: release
      env: R_CODECOV=true
    - r: devel
      env: _R_CHECK_LENGTH_1_LOGIC2_=TRUE

r_packages:
  - covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

env:
  global:
     - R_LIBS="https://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""

notifications:
  email:
    on_success: never
    on_failure: never
  
