language: r
sudo: false
cache: packages
dist: trusty

r_binary_packages:
- covr

after_success:
- Rscript -e 'covr::codecov()'

env:
  global:
  - R_BUILD_ARGS="--no-manual"
  - R_CHECK_ARGS="--as-cran --no-manual"

notifications:
  email:
    on_success: never
    on_failure: never
  
